[package]
name = "trname"
version = "0.1.0"
edition = "2021"
authors = ["syr <user@syrflover.co>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
inquire = "0.7"
regex = "1.10"
